### PR TITLE
Fix void pointer types to build with go 1.3

### LINKED ISSUE #22: Cannot build with go 1.3
Looks like it does not like the void pointers being uses to interop with GEOS

```
$ go version
go version go1.3 darwin/amd64
$ ./build
code.google.com/p/gcfg (download)
github.com/lib/pq (download)
github.com/ungerik/go-rest (download)
code.google.com/p/gcfg/token
code.google.com/p/gcfg/types
github.com/lib/pq/oid
github.com/ungerik/go-rest
github.com/lib/pq
code.google.com/p/gcfg/scanner
code.google.com/p/gcfg
github.com/azavea/ecobenefits/eco
# github.com/azavea/ecobenefits/eco
gopath/src/github.com/azavea/ecobenefits/eco/geom.go:41: cannot use g.preped (type *[0]byte) as type *C.struct_GEOSPrepGeom_t in argument to _Cfunc_GEOSPreparedContains
gopath/src/github.com/azavea/ecobenefits/eco/geom.go:41: cannot use p.pointptr (type *[0]byte) as type *C.struct_GEOSGeom_t in argument to _Cfunc_GEOSPreparedContains
gopath/src/github.com/azavea/ecobenefits/eco/geom.go:74: cannot use geom (type *C.struct_GEOSGeom_t) as type *[0]byte in field value
gopath/src/github.com/azavea/ecobenefits/eco/geom.go:74: cannot use prepgeom (type *C.struct_GEOSPrepGeom_t) as type *[0]byte in field value
gopath/src/github.com/azavea/ecobenefits/eco/geom.go:87: cannot use coordseqptr (type *C.struct_GEOSCoordSeq_t) as type *[0]byte in field value
gopath/src/github.com/azavea/ecobenefits/eco/geom.go:87: cannot use pointptr (type *C.struct_GEOSGeom_t) as type *[0]byte in field value
gopath/src/github.com/azavea/ecobenefits/eco/geom.go:91: cannot use g.geom (type *[0]byte) as type *C.struct_GEOSGeom_t in argument to _Cfunc_GEOSGetCentroid
gopath/src/github.com/azavea/ecobenefits/eco/geom.go:114: cannot use geom.preped (type *[0]byte) as type *C.struct_GEOSPrepGeom_t in argument to _Cfunc_GEOSPreparedGeom_destroy
gopath/src/github.com/azavea/ecobenefits/eco/geom.go:115: cannot use geom.geom (type *[0]byte) as type *C.struct_GEOSGeom_t in argument to _Cfunc_GEOSGeom_destroy
gopath/src/github.com/azavea/ecobenefits/eco/geom.go:119: cannot use p.pointptr (type *[0]byte) as type *C.struct_GEOSGeom_t in argument to _Cfunc_GEOSGeom_destroy
gopath/src/github.com/azavea/ecobenefits/eco/geom.go:119: too many errors
```

...downgrade...

```
$ go version
go version go1.2.2 darwin/amd64
$ ./build
code.google.com/p/gcfg (download)
github.com/lib/pq (download)
github.com/ungerik/go-rest (download)
code.google.com/p/gcfg/token
code.google.com/p/gcfg/types
github.com/lib/pq/oid
github.com/ungerik/go-rest
code.google.com/p/gcfg/scanner
github.com/lib/pq
code.google.com/p/gcfg
github.com/azavea/ecobenefits/eco
github.com/azavea/ecobenefits
ok  	command-line-arguments	0.089s

### PR DESCRIPTION
**Pull request by steventlamb**
fixes #22 on github

tested to also build inside the VM with go 1.2

### CODE REVIEW

**Comment by maurizi** [comment]
Want to try updating our `.travis.yml` file to build with Go 1.3 as well?

**Comment by maurizi** [comment]
Otherwise, looks good to me.  This squares with what I've read about using C in Go.

**Comment by steventlamb** [comment]
Added 1.3 and 1.4 to `.travis.yml`. If 1.4 fails, we can drop it and add a separate issue.

**Comment by jwalgran** [comment]
+1 I rebuilt and ran the service on my vm with both 1.3 and 1.4 with no errors. Output numbers are identical.

**Pull request merged**
