### PR TITLE
Topic/drop csvs

### PR DESCRIPTION
**Pull request by steventlamb**

### CODE REVIEW

**Comment by steventlamb** [comment]
The first commit is connected to another PR and can be reviewed separately.

**Comment by jwalgran** [comment]
Curious about the motivation for this.

**Comment by steventlamb** [comment]
It's hard to see in the diff, because so many files get added and deleted, but there was a TODO in the original source to dump the data as JSON and get rid of the CSVs. There's some tricky CSV massaging code that runs every time when we read them, which is not necessary with a clean JSON dump. Now that we have JSON assets, that code can be (and is) removed, which is nice.

That's the background. As for why I've chosen to take this up - since I'm porting this to another language, it didn't make sense to recreate the CSV massaging workaround when I could use clean JSON data, so I made this fix first.

**Comment by jwalgran** [comment]
``io.go`` still mentions "csv"s in a few code comments

**Comment by jwalgran** [comment]
This looks good, and the unit tests pass. I am going to run it with some production data to make sure the numbers match up with the old csv-powered version.

**Comment by jwalgran** [comment]
+1 calculations match production

screen shot 2015-04-24 at 3 46 19 pm

**Pull request merged**
