### PR TITLE
Topic/misc updates

### PR DESCRIPTION
**Pull request by steventlamb**

### CODE REVIEW

**Comment by steventlamb** [comment]
This doesn't quite work. 
```
2015/01/12 18:07:04 Server listening at 127.0.0.1:13000
2015/01/12 18:07:14 POST /eco_summary.json
2015/01/12 18:07:14 ERROR: sql: database is closed
2015/01/12 18:17:26 POST /eco_summary.json
2015/01/12 18:17:26 ERROR: sql: database is closed
```

When everything was in the same file, a dbcontext was opened at the beginning and a deferred closing statement was included. Then the variable was closed-over in the inline handlers. This just worked.

Now, the code appears to work the same, but the database connection is closed by the time an endpoint tries to use it.

Looking into this.

**Comment by steventlamb** [comment]
Fixed in latest push.

**Comment by steventlamb** [comment]
I have not yet. I was planning to do so in another commit before merging. Didn't want to add noise to the pull.

**Comment by steventlamb** [comment]
This has been rebased, formatted with `go fmt`, and initial issues have been addressed. I think it's ready to merge after some review and some smoke testing on live data.

**Comment by kdeloach** [comment]
My knowledge of Go is limited, but the tests all pass, and the code looks solid.

**Comment by kdeloach** [comment]
+1

**Comment by jwalgran** [comment]
+1 This version of the eco service appears to generate the correct output. When their are divergent numbers, it is because my data snapshot it old

screen shot 2015-02-20 at 1 50 58 pm
screen shot 2015-02-20 at 1 49 47 pm
screen shot 2015-02-20 at 1 49 10 pm
screen shot 2015-02-20 at 1 48 33 pm
screen shot 2015-02-20 at 1 47 48 pm
screen shot 2015-02-20 at 1 47 05 pm
screen shot 2015-02-20 at 1 46 59 pm

**Pull request merged**
